// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkndpuehqntqsjwvtqlt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdrbmRwdWVocW50cXNqd3Z0cWx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1MTUxMDAsImV4cCI6MjA1MTA5MTEwMH0.aA7p3jD0eYSficqcjY3xrv2YPU6BJ98Ne1WdgzWijFA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);